services:
  weechat:
    container_name: weechat
    image: weechat/weechat:latest-slim
    ports:
      - "6696:6696"
    command: ["sleep", "infinity"]
    network_mode: "host"
#    networks:
#        - irc_network

  weechat2:
    container_name: weechat2
    image: weechat/weechat:latest-slim
    ports:
      - "6697:6696"
    command: ["sleep", "infinity"]
    network_mode: "host"
#  irc:
#    container_name: irc
#    build:
#        context: .
#        dockerfile: Dockerfile
#    ports:
#        - "6697:6697"
#    depends_on:
#      - weechat
#    command: ["sleep", "infinity"]
#    networks:
#        - irc_network

#networks:
#    irc_network:
#        driver: bridge